#!/usr/bin/env proc

proc fizzbuzz(x) {
	if x % 15 == 0 {
		printfizz();
		printbuzz();
		PutChar('\n');
	} else if x % 3 == 0 {
		printfizz();
		PutChar('\n');
	} else if x % 5 == 0 {
		printbuzz();
		PutChar('\n');
	} else {
		PutInt(x);
	}
}

proc printfizz() { PutChar('F');PutChar('i');PutChar('z');PutChar('z'); }
proc printbuzz() { PutChar('B');PutChar('u');PutChar('z');PutChar('z'); }

proc main() {
	int i = 1;
	while i <= 100 {
		fizzbuzz(i);
		i += 1;
	}
}
